# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2'

services:
  # PHP & apache container using offical Docker PHP iamge
  web:
    build: .
    links:
      - db
    ports:
      # Expose Emoncms on localhost port 8080
      - 8080:80
    volumes:
      # Mount emoncms files from local FS for dev
       - ./www:/var/www/heatpumpmonitororg
    env_file:
      # Use default enviroment variables file for dev
      - 'default.docker-env'

  db:
    image: mariadb:11.0
    environment:
      - "MYSQL_HOST=localhost"
      - "MARIADB_AUTO_UPGRADE=1"
      - "MARIADB_INITDB_SKIP_TZINFO=1"
    env_file:
      - 'default.docker-env'
    volumes:
      - emon-db-data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "10m"

volumes:
  emon-db-data:
    driver: local

